//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Ticket.AsyncEnterpriseReports.ComplexTypes {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ticket.corporativo/params/reports", IsNullable=false)]
    public partial class PedidoPATDetalhadoPorNomeArquivo : ReportRequest {
        
        private string nomeArquivoField;
        
        /// <remarks/>
        public string NomeArquivo {
            get {
                return this.nomeArquivoField;
            }
            set {
                this.nomeArquivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PedidoPATDetalhadoPorNomeArquivo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    public partial class ReportRequest {
        
        private string sourceSystemField;
        
        private string replyToField;
        
        private string correlationIDField;
        
        private string relativePathDestinationField;
        
        private MediaType acceptedMediaTypeField;
        
        private BusinessInformation businessInformationField;
        
        private ResponseProvider providerField;
        
        /// <remarks/>
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        public string ReplyTo {
            get {
                return this.replyToField;
            }
            set {
                this.replyToField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public string RelativePathDestination {
            get {
                return this.relativePathDestinationField;
            }
            set {
                this.relativePathDestinationField = value;
            }
        }
        
        /// <remarks/>
        public MediaType AcceptedMediaType {
            get {
                return this.acceptedMediaTypeField;
            }
            set {
                this.acceptedMediaTypeField = value;
            }
        }
        
        /// <remarks/>
        public BusinessInformation BusinessInformation {
            get {
                return this.businessInformationField;
            }
            set {
                this.businessInformationField = value;
            }
        }
        
        /// <remarks/>
        public ResponseProvider Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    public enum MediaType {
        
        /// <remarks/>
        XML,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    public enum BusinessInformation {
        
        /// <remarks/>
        Order,
        
        /// <remarks/>
        Client,
        
        /// <remarks/>
        Beneficiary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    public enum ResponseProvider {
        
        /// <remarks/>
        MessageQueue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    public partial class ResponseStatus {
        
        private string detailField;
        
        private StatusCode statusCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        public StatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    public enum StatusCode {
        
        /// <remarks/>
        _201_Created,
        
        /// <remarks/>
        _204_No_Content,
        
        /// <remarks/>
        _400_Bad_Request,
        
        /// <remarks/>
        _412_Pre_Condition_Failed,
        
        /// <remarks/>
        _415_Unsupported_Media_Type,
        
        /// <remarks/>
        _500_Internal_Server_Error,
        
        /// <remarks/>
        _501_Not_Implemented,
        
        /// <remarks/>
        _504_Remote_Resource_Timeout,
        
        /// <remarks/>
        _507_Insuficient_Storage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ticket.corporativo/params/reports", IsNullable=false)]
    public partial class ListaPedidoPATDetalhadoPorNomeArquivo {
        
        private PedidoPATDetalhadoPorNomeArquivo[] pedidoPATDetalhadoPorNomeArquivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PedidoPATDetalhadoPorNomeArquivo")]
        public PedidoPATDetalhadoPorNomeArquivo[] PedidoPATDetalhadoPorNomeArquivo {
            get {
                return this.pedidoPATDetalhadoPorNomeArquivoField;
            }
            set {
                this.pedidoPATDetalhadoPorNomeArquivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ticket.corporativo/params/reports", IsNullable=false)]
    public partial class ReportResponse {
        
        private ReportRequest requestDataField;
        
        private string reportFilePathField;
        
        private ResponseStatus statusField;
        
        /// <remarks/>
        public ReportRequest RequestData {
            get {
                return this.requestDataField;
            }
            set {
                this.requestDataField = value;
            }
        }
        
        /// <remarks/>
        public string ReportFilePath {
            get {
                return this.reportFilePathField;
            }
            set {
                this.reportFilePathField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/params/reports")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ticket.corporativo/params/reports", IsNullable=false)]
    public partial class BadPayloadMessage {
        
        private string rawRequestDataField;
        
        private ResponseStatus statusField;
        
        /// <remarks/>
        public string RawRequestData {
            get {
                return this.rawRequestDataField;
            }
            set {
                this.rawRequestDataField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
}
