//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Ticket.AsyncEnterpriseReports.Pedidos.Domain.ComplexTypes {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ticket.corporativo/pedido", IsNullable=false)]
    public partial class ListaPedidosPATDetalhados {
        
        private PedidoPATDetalhado[] pedidoPATDetalhadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PedidoPATDetalhado", IsNullable=true)]
        public PedidoPATDetalhado[] PedidoPATDetalhado {
            get {
                return this.pedidoPATDetalhadoField;
            }
            set {
                this.pedidoPATDetalhadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class PedidoPATDetalhado {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private Arquivo arquivoField;
        
        private ClienteVO clienteField;
        
        private ContratoClienteVO contratoField;
        
        private ProdutoVO produtoField;
        
        private System.Nullable<System.DateTime> dataPedidoField;
        
        private bool dataPedidoFieldSpecified;
        
        private System.Nullable<System.DateTime> dataEntregaField;
        
        private bool dataEntregaFieldSpecified;
        
        private string numeroPedidoClienteField;
        
        private string numeroPedidoField;
        
        private StatusPedido statusField;
        
        private Tarifacao[] tarifacoesField;
        
        private Unidade[] unidadesField;
        
        private System.Nullable<decimal> valorTotalField;
        
        private bool valorTotalFieldSpecified;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Arquivo Arquivo {
            get {
                return this.arquivoField;
            }
            set {
                this.arquivoField = value;
            }
        }
        
        /// <remarks/>
        public ClienteVO Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public ContratoClienteVO Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        public ProdutoVO Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataPedido {
            get {
                return this.dataPedidoField;
            }
            set {
                this.dataPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataPedidoSpecified {
            get {
                return this.dataPedidoFieldSpecified;
            }
            set {
                this.dataPedidoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataEntrega {
            get {
                return this.dataEntregaField;
            }
            set {
                this.dataEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataEntregaSpecified {
            get {
                return this.dataEntregaFieldSpecified;
            }
            set {
                this.dataEntregaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NumeroPedidoCliente {
            get {
                return this.numeroPedidoClienteField;
            }
            set {
                this.numeroPedidoClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroPedido {
            get {
                return this.numeroPedidoField;
            }
            set {
                this.numeroPedidoField = value;
            }
        }
        
        /// <remarks/>
        public StatusPedido Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Tarifacao[] Tarifacoes {
            get {
                return this.tarifacoesField;
            }
            set {
                this.tarifacoesField = value;
            }
        }
        
        /// <remarks/>
        public Unidade[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorTotalSpecified {
            get {
                return this.valorTotalFieldSpecified;
            }
            set {
                this.valorTotalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class Arquivo {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        private string sistemaOrigemField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string SistemaOrigem {
            get {
                return this.sistemaOrigemField;
            }
            set {
                this.sistemaOrigemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class Beneficio {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long unidadeIdField;
        
        private bool unidadeIdFieldSpecified;
        
        private long pedidoIdField;
        
        private bool pedidoIdFieldSpecified;
        
        private System.Nullable<long> identificacaoBeneficiarioField;
        
        private bool identificacaoBeneficiarioFieldSpecified;
        
        private string nomeBeneficiarioField;
        
        private string nomeResumidoField;
        
        private string codigoDepartamentoField;
        
        private string nomeDepartamentoField;
        
        private System.Nullable<decimal> valorBeneficioField;
        
        private bool valorBeneficioFieldSpecified;
        
        private System.Nullable<long> cPFField;
        
        private bool cPFFieldSpecified;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long UnidadeId {
            get {
                return this.unidadeIdField;
            }
            set {
                this.unidadeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnidadeIdSpecified {
            get {
                return this.unidadeIdFieldSpecified;
            }
            set {
                this.unidadeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long PedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PedidoIdSpecified {
            get {
                return this.pedidoIdFieldSpecified;
            }
            set {
                this.pedidoIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdentificacaoBeneficiario {
            get {
                return this.identificacaoBeneficiarioField;
            }
            set {
                this.identificacaoBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificacaoBeneficiarioSpecified {
            get {
                return this.identificacaoBeneficiarioFieldSpecified;
            }
            set {
                this.identificacaoBeneficiarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NomeBeneficiario {
            get {
                return this.nomeBeneficiarioField;
            }
            set {
                this.nomeBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        public string NomeResumido {
            get {
                return this.nomeResumidoField;
            }
            set {
                this.nomeResumidoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeDepartamento {
            get {
                return this.nomeDepartamentoField;
            }
            set {
                this.nomeDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorBeneficio {
            get {
                return this.valorBeneficioField;
            }
            set {
                this.valorBeneficioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorBeneficioSpecified {
            get {
                return this.valorBeneficioFieldSpecified;
            }
            set {
                this.valorBeneficioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CPFSpecified {
            get {
                return this.cPFFieldSpecified;
            }
            set {
                this.cPFFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class Unidade {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long pedidoIdField;
        
        private bool pedidoIdFieldSpecified;
        
        private string nomeUnidadeField;
        
        private string codigoUnidadeEntregaField;
        
        private System.Nullable<System.DateTime> liberacaoCreditoField;
        
        private bool liberacaoCreditoFieldSpecified;
        
        private Beneficio[] beneficiosField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long PedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PedidoIdSpecified {
            get {
                return this.pedidoIdFieldSpecified;
            }
            set {
                this.pedidoIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NomeUnidade {
            get {
                return this.nomeUnidadeField;
            }
            set {
                this.nomeUnidadeField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoUnidadeEntrega {
            get {
                return this.codigoUnidadeEntregaField;
            }
            set {
                this.codigoUnidadeEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LiberacaoCredito {
            get {
                return this.liberacaoCreditoField;
            }
            set {
                this.liberacaoCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LiberacaoCreditoSpecified {
            get {
                return this.liberacaoCreditoFieldSpecified;
            }
            set {
                this.liberacaoCreditoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Beneficio[] Beneficios {
            get {
                return this.beneficiosField;
            }
            set {
                this.beneficiosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class Tarifacao {
        
        private System.Nullable<int> quantidadeItensField;
        
        private bool quantidadeItensFieldSpecified;
        
        private System.Nullable<decimal> valorField;
        
        private bool valorFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QuantidadeItens {
            get {
                return this.quantidadeItensField;
            }
            set {
                this.quantidadeItensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantidadeItensSpecified {
            get {
                return this.quantidadeItensFieldSpecified;
            }
            set {
                this.quantidadeItensFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class StatusPedido {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class ProdutoVO {
        
        private string descricaoField;
        
        private string codigoERPField;
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoERP {
            get {
                return this.codigoERPField;
            }
            set {
                this.codigoERPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class ContratoClienteVO {
        
        private string numContratoField;
        
        /// <remarks/>
        public string NumContrato {
            get {
                return this.numContratoField;
            }
            set {
                this.numContratoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ticket.corporativo/pedido")]
    public partial class ClienteVO {
        
        private string razaoSocialField;
        
        private string cnpjField;
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
    }
}
